In [3]:
import pandas as pd
import numpy as np

# helpful youtube for data wrangling https://www.youtube.com/watch?v=x0Sy6Kl0Mzw
# Replace 'your_file.csv.gz' with the actual file path
file_path = 'data_dump/SR36.csv.gz'

# Read the compressed CSV file into a pandas DataFrame
df = pd.read_csv(file_path, compression='gzip')

# Now 'df' contains the data from the CSV file
df.head()

,utc_timestamp,local_timestamp,network_id,source_id,length_mi,freeflow_mph,primary_source,subsegment,closed,vehicle_type,avg_speed_mph,stdev_speed_mph,source_ref
0,2023-09-28 01:55:00,2023-09-27 19:55:00,S201R4,-124041713,0.053997,35.001839,True,False,False,all,27.800147,NaN,link
1,2023-09-22 01:10:00,2023-09-21 19:10:00,S201R4,-124041713,0.053997,35.001839,True,False,False,all,28.399149,NaN,link
2,2023-09-22 01:40:00,2023-09-21 19:40:00,S201R4,-124041713,0.053997,35.001839,True,False,False,all,29.999801,NaN,link
3,2023-09-19 06:20:00,2023-09-19 00:20:00,S201R4,1198018451,0.019320,39.997664,True,True,False,all,41.998479,NaN,link
4,2023-09-19 06:20:00,2023-09-19 00:20:00,S201R4,1198018450,0.026915,39.997664,True,True,False,all,41.998479,NaN,link

## Get list of routes
I need to match route names and IDs with either network_id or source_id...

In [6]:
#check the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2217384 entries, 0 to 2217383
Data columns (total 13 columns):
 #   Column           Dtype
---  ------           -----
 0   utc_timestamp    object
 1   local_timestamp  object
 2   network_id       object
 3   source_id        object
 4   length_mi        float64
 5   freeflow_mph     float64
 6   primary_source   bool
 7   subsegment       bool
 8   closed           bool
 9   vehicle_type     object
 10  avg_speed_mph    float64
 11  stdev_speed_mph  float64
 12  source_ref       object
dtypes: bool(3), float64(4), object(6)
memory usage: 175.5+ MB

In [9]:
# replace function. I wonder if I can replace with a whole file...
# I'd like to add route ID 
# df['network_id'] = df['network_id'].replace({'something': 'better', 'other': 'best'})

# or I can create columns
df['Travel_time_sec'] = df['length_mi'] / df['avg_speed_mph']*3600
df['Delay_sec'] = df['Travel_time_sec'] - df['length_mi'] / df['freeflow_mph'] * 3600
df.head()

,utc_timestamp,local_timestamp,network_id,source_id,length_mi,freeflow_mph,primary_source,subsegment,closed,vehicle_type,avg_speed_mph,stdev_speed_mph,source_ref,Travel_time_sec,Delay_sec
0,2023-09-28 01:55:00,2023-09-27 19:55:00,S201R4,-124041713,0.053997,35.001839,True,False,False,all,27.800147,NaN,link,6.992401,1.438699
1,2023-09-22 01:10:00,2023-09-21 19:10:00,S201R4,-124041713,0.053997,35.001839,True,False,False,all,28.399149,NaN,link,6.844915,1.291214
2,2023-09-22 01:40:00,2023-09-21 19:40:00,S201R4,-124041713,0.053997,35.001839,True,False,False,all,29.999801,NaN,link,6.479702,0.926000
3,2023-09-19 06:20:00,2023-09-19 00:20:00,S201R4,1198018451,0.019320,39.997664,True,True,False,all,41.998479,NaN,link,1.656065,-0.082842
4,2023-09-19 06:20:00,2023-09-19 00:20:00,S201R4,1198018450,0.026915,39.997664,True,True,False,all,41.998479,NaN,link,2.307103,-0.115409